### ISSUE TITLE
Add Test262 for JavaScript parser

### ISSUE THREAD

**Issue by tom-sherman** [romejs/rome#36]
Prior art in this space:

https://github.com/babel/babel-test262-runner

**Comment by sebmck** [comment]
test262 is only relevant for Babel because that runner is compiling and executing files. We don't currently do that. Checking if we can just parse something isn't super high signal since there are many scenarios where we fail which is excepted but in the wrong way that was intended. We already have enough coverage with the Babel-imported tests. I found [`test262-parser-tests`](https://github.com/tc39/test262-parser-tests) but it seems to be dead. We should definitely look at importing some spec tests though.
