### ISSUE TITLE
The config command seems to be broken

### ISSUE THREAD

**Issue by MareikeTaeubner** [romejs/rome#508]
Description:

Using the config command to add a section to the rome.rjson does not seem to work right now.
I tried to add `lint` with `rome config enable lint` and `rome config enable lint.enabled` (old variant). Both resulted in an error:

```
rome config enable lint
√ Setting lint to true in the project config rome.rjson
× Error occured while testing new project config. Your changes have not been saved.

 rome.rjson:2:6 parse/json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × Expected an object here but got a boolean at lint

    1 │ name: "test"
  > 2 │ lint: true
      │       ^^^^
    3 │ version: "^0.0.25"

  i You likely wanted `{"enabled": true}` instead

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
× Found 1 problem

 rome config enable lint.enabled
√ Setting lint.enabled to true in the project config rome.rjson
× Error occured while testing new project config. Your changes have not been saved.

 rome.rjson:2:7 parse/json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  × Unknown enabled config property at lint

    1 │ name: "test"
  > 2 │ lint: {enabled: true}
      │        ^^^^^^^
    3 │ version: "^0.0.25"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
× Found 1 problem
```

## Steps To Reproduce

1. create rome.rjson with `rome init`
2. try to add the `lint` section via `rome config enable lint`

## Expected Results

The `lint` section is added to the rome.rjson.

**Comment by sebmck** [comment]
Docs aren't up to date, which I assume is where you got `rome config enable lint` from.

`rome config set key value` basically just does `config[key] = String(value)`. Since it only works on strings we have `enable` and `disable that do: `config[key] = true/false;`.

We removed the ability to have to enable/disable `lint` as for Rome's initial release it will be the only function. If it's really necessary later then we could add it back as we polish and release the other parts of Rome, but for now it was just unnecessary complexity.

**Comment by bitpshr** [comment]
There are a few issues causing confusion:

1. The documentation describes an interactive `init` command that is not currently interactive. 
2. The documentation describes a `config` command that is not currently capable of updating any supported configuration property.

We should definitely verify the correctness and applicability of all documentation prior to a published release. think that we should leave this open to make sure these documentation updates get done as part of #496.

**Comment by sebmck** [comment]
> The documentation describes a config command that is not currently capable of updating any supported configuration property.

It does. You can do `rome config set name whatever` and it will work. There are a lot of project config options that aren't relevant for linting though where it would be the most valuable.

**Comment by MareikeTaeubner** [comment]
I'm not sure what to do with the ticket right now, because it was obviously a mistake on my side (do I need to close it?)

On the other hand was the printed error message not really helpful in that situation. With `config -h` not helping either - I was really, really confused. Maybe the help section could be expanded in a later version?

**Comment by bitpshr** [comment]
The CLI is in a confusing place since linting and formatting are the primary functions of Rome for its initial release, but only unrelated (and undocumented) project options can be configured. This means that even if a consumer guesses a supported config property (e.g. `name`), configuring that property using `rome config set name foo` updates the config, but otherwise has no effect on the linting and formatting that Rome currently exposes.

We definitely need to clean up the `rome init` documentation since it's not interactive. Additionally, if any of the configuration options currently supported by `rome config` have an actual effect on Rome's current, public functionality, we should document those options somewhere. Otherwise, I feel like we should not document `rome config` at all if it's only capable of setting options that have no effect. This would've mitigated the original issue reported by @MareikeTaeubner.

**Comment by sebmck** [comment]
The `config` command should be stable. I've added a command example to all the project config documentation on the website. We should make the `config` command the recommended way to add/modify configuration since it's extremely approachable.
