### ISSUE TITLE
LSPServer delay when opening new workspace

### ISSUE THREAD

**Issue by yassere** [romejs/rome#651]
When a workspace is opened in VS Code with the Rome extension, the LSPServer begins a `Linter#watch` of the entire project. During that initial lint run, format-on-save is unresponsive, and no diagnostics will be published until the lint run is complete.

Is it necessary that the LSPServer watch the filesystem instead of just responding to `textDocument/didOpen`, `didChange`, `didClose`, and `formatting` messages?

If the idea is that we want to build a cache for the whole project, could that be done in the background while giving higher priority to files that are open in the editor?

**Comment by sebmck** [comment]
Rome relies heavily on the memory file system so we can have fast synchronous calls to see if a file exists, get its stats etc.

Without having it initialized we can’t perform any operation on a file because:

- We don’t know if it’s a part of a sub project. We only start watching the file system which triggers the project loading at the “highest” folder that we’ve found a project in.
- We don’t know what package.json a file is associated with. We need this to disambiguate whether some files should be parsed as a module.

We could do hard file system calls for these but it would require having two code paths and is expensive to maintain. The project loading was something I recently refactored and before it was more similar to what you’re describing but it was unpredictable because there were race conditions with loading of projects.

**Comment by yassere** [comment]
I don't think that the delayed diagnostics are a very big deal, but I think we should take a look at the unresponsive format-on-save. If I try to save a file while the initial lint run is in progress, VS Code gives me a `Saving 'foo.ts': Running 'Rome' Formatter` message that persists until I hit cancel, and it seems to disrupt the initialization process.

Ideally, we could somehow prioritize just `textDocument/formatting` requests so that formatting is always possible. If that's not practical, could we return `null` for formatting requests within projects that are still initializing?

**Comment by sebmck** [comment]
> Ideally, we could somehow prioritize just `textDocument/formatting` requests so that formatting is always possible.

I don't think it is without some serious architecture changes (or rather supplements, partial hydration of things like project configs, manifests etc, for operation on only a single file).

> If that's not practical, could we return null for formatting requests within projects that are still initializing?

That sounds good. I'm actually not too sure why it would hang after initialization. We should only be blocking under the project is ready.
